services:
  - type: web
    name: quotesai-backend
    env: python
    plan: free
    rootDir: ./backend
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python migrate_db.py && uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright
      - key: DATABASE_URL
        fromDatabase:
          name: quotesai-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://quotes-ai-eight.vercel.app
      - key: LLM_API_KEY
        sync: false # Render will prompt you for this value
      - key: DATA_DIR
        value: ./data
      - key: STORAGE_ACCESS_KEY
        sync: false
      - key: GMAIL_ADDRESS
        sync: false # Render will prompt you for your Gmail address
      - key: GMAIL_APP_PASSWORD
        sync: false # Render will prompt you for your App Password

databases:
  - name: quotesai-db
    plan: free
    databaseName: quotesdb
    user: quotes_user
